### PR TITLE
Query Multiple Tables

### PR DESCRIPTION
**Pull request by Dinma-Faith-zz**
In this Milestone, I add new tables and foreign key columns to my existing animal's table to model one-to-many relations. Afterward, I use JOIN to query the data.

### Project requirements
- Create a table named `owners` with the following columns:
  - `id`: integer (set it as autoincremented PRIMARY KEY)
  - `full_name`: string
  - `age`: integer
  
create-owners-table

- Create a table named `species` with the following columns:
  - `id`: integer (set it as autoincremented PRIMARY KEY)
  - `name`: string
create-owners-and-species-table

- Modify `animals` table:
  - Make sure that id is set as autoincremented PRIMARY KEY
  - Remove column `species`
  - Add column `species_id` which is a foreign key referencing `species` table
  - Add column `owner_id` which is a foreign key referencing the `owners` table
- Remember all this goes in `schema.sql`.
Modify-animal-table

- Insert the following data into the `owners` table:
  - Sam Smith 34 years old.
  - Jennifer Orwell 19 years old.
  - Bob 45 years old.
  - Melody Pond 77 years old.
  - Dean Winchester 14 years old.
  - Jodie Whittaker 38 years old.
insert-into-owners

- Insert the following data into the `species` table:
  - Pokemon
  - Digimon
insert-into-species

- Modify your inserted animals so it includes the `species_id` value:
  - If the name ends in "mon" it will be Digimon
  - All other animals are Pokemon
Modify-species_id-val

- Modify your inserted animals to include owner information (`owner_id`):
  - Sam Smith owns Agumon.
  - Jennifer Orwell owns Gabumon and Pikachu.
  - Bob owns Devimon and Plantmon.
  - Melody Pond owns Charmander, Squirtle, and Blossom.
  - Dean Winchester owns Angemon and Boarmon.
- Remember these insertions and modifications happen in `data.sql`.
Modify-animals-owner_id

- Write queries (using `JOIN`) to answer the following questions:
  - What animals belong to Melody Pond?
  
MelodyPond-animals

  - List of all animals that are pokemon (their type is Pokemon).
type-pokemon

  - List all owners and their animals, remember to include those that don't own any animal.
owners-and-animals

  - How many animals are there per species?
Total-per-species

  - List all Digimon owned by Jennifer Orwell.
Jennifer-Digimon

  - List all animals owned by Dean Winchester that haven't tried to escape.
Dean-not-escape

  - Who owns the most animals?
Most-animals

Comments and Suggestions are welcome
Thank you

### CODE REVIEW

**Review by Whoistolu — CHANGES_REQUESTED** [review]
Hi @Dinma-Faith 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] Kindly ensure that you add screenshots of your query results to your Pull Request description as it is a core requirement for this milestone.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Dinma-Faith-zz** [comment]
@Whoistolu Thanks for the review. I added the screenshots to the PR but forgot to commit before submission. 
Thanks again

**Review by Whoistolu — APPROVED** [review]
### Hi @Dinma-Faith 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Dinma-Faith-zz** [comment]
@Whoistolu Thank you

**Pull request merged**
